/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/alta`; params?: Router.UnknownInputParams; } | { pathname: `/codeqr`; params?: Router.UnknownInputParams; } | { pathname: `/Details`; params?: Router.UnknownInputParams; } | { pathname: `/movimientos`; params?: Router.UnknownInputParams; } | { pathname: `/pago`; params?: Router.UnknownInputParams; } | { pathname: `/tranferencia`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/_layout2` | `/_layout2`; params?: Router.UnknownInputParams; } | { pathname: `/cobro`; params?: Router.UnknownInputParams; } | { pathname: `/scanner`; params?: Router.UnknownInputParams; } | { pathname: `/scanner/Overlay`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/alta`; params?: Router.UnknownOutputParams; } | { pathname: `/codeqr`; params?: Router.UnknownOutputParams; } | { pathname: `/Details`; params?: Router.UnknownOutputParams; } | { pathname: `/movimientos`; params?: Router.UnknownOutputParams; } | { pathname: `/pago`; params?: Router.UnknownOutputParams; } | { pathname: `/tranferencia`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/_layout2` | `/_layout2`; params?: Router.UnknownOutputParams; } | { pathname: `/cobro`; params?: Router.UnknownOutputParams; } | { pathname: `/scanner`; params?: Router.UnknownOutputParams; } | { pathname: `/scanner/Overlay`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/alta${`?${string}` | `#${string}` | ''}` | `/codeqr${`?${string}` | `#${string}` | ''}` | `/Details${`?${string}` | `#${string}` | ''}` | `/movimientos${`?${string}` | `#${string}` | ''}` | `/pago${`?${string}` | `#${string}` | ''}` | `/tranferencia${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/_layout2${`?${string}` | `#${string}` | ''}` | `/_layout2${`?${string}` | `#${string}` | ''}` | `/cobro${`?${string}` | `#${string}` | ''}` | `/scanner${`?${string}` | `#${string}` | ''}` | `/scanner/Overlay${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/alta`; params?: Router.UnknownInputParams; } | { pathname: `/codeqr`; params?: Router.UnknownInputParams; } | { pathname: `/Details`; params?: Router.UnknownInputParams; } | { pathname: `/movimientos`; params?: Router.UnknownInputParams; } | { pathname: `/pago`; params?: Router.UnknownInputParams; } | { pathname: `/tranferencia`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/_layout2` | `/_layout2`; params?: Router.UnknownInputParams; } | { pathname: `/cobro`; params?: Router.UnknownInputParams; } | { pathname: `/scanner`; params?: Router.UnknownInputParams; } | { pathname: `/scanner/Overlay`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
